//===== (Imports) ======
import { StyleSheet } from "react-native";
import {
  AUTH_ACCENT_ORANGE,
  AUTH_FONT,
} from "@/features/auth/constants/styles";

//===== (LoginScreen Styles) ======
const styles = StyleSheet.create({
  outerContainer: {
    flex: 1,
    backgroundColor: "#000000",
  },
  backgroundImage: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
  backgroundImageStyle: {
    resizeMode: "cover",
    opacity: 0.55,
  },
  fullOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(12, 18, 34, 0.50)",
  },
  safeArea: {
    flex: 1,
  },
  container: {
    flex: 1,
  },
  screen: {
    flex: 1,
    width: "100%",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  brandBlock: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.35)",
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 22,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.28)",
    alignSelf: "center",
    maxWidth: "94%",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  logoImage: {
    width: 265,
    height: 101,
    marginBottom: 4,
  },
  welcome: {
    color: "#FFFFFF",
    fontFamily: AUTH_FONT,
    fontSize: 22,
    fontWeight: "700",
    letterSpacing: -0.3,
    textAlign: "center",
    textShadowColor: "rgba(0, 0, 0, 0.45)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  subtitle: {
    color: "rgba(255, 255, 255, 0.95)",
    fontFamily: AUTH_FONT,
    fontSize: 13,
    marginTop: 3,
    textAlign: "center",
    paddingHorizontal: 10,
    textShadowColor: "rgba(0, 0, 0, 0.35)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  formSection: {
    width: "100%",
    paddingHorizontal: 0,
  },
  formCard: {
    width: "100%",
    maxWidth: 430,
    alignSelf: "center",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 24,
    padding: 22,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 3,
  },
  label: {
    color: "#F8FAFC",
    fontFamily: AUTH_FONT,
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 6,
  },
  inputWrapper: {
    minHeight: 48,
    backgroundColor: "rgba(248, 250, 252, 0.95)",
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.15)",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
  },
  inputWrapperFocused: {
    borderColor: "#18AEE6",
    backgroundColor: "#FFFFFF",
  },
  inputIcon: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    minHeight: 44,
    color: "#0F172A",
    fontFamily: AUTH_FONT,
    fontSize: 15,
    paddingVertical: 8,
  },
  passwordToggle: {
    padding: 6,
    marginLeft: 4,
  },
  rememberAndForgotRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 0,
    marginBottom: 16,
  },
  rememberPressable: {
    flexDirection: "row",
    alignItems: "center",
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    backgroundColor: "#FFFFFF",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.6)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
  },
  checkboxActive: {
    backgroundColor: "#18AEE6",
    borderColor: "#18AEE6",
  },
  rememberText: {
    color: "#F8FAFC",
    fontFamily: AUTH_FONT,
    fontSize: 14,
    fontWeight: "500",
  },
  forgotPasswordLink: {
    color: AUTH_ACCENT_ORANGE,
    fontFamily: AUTH_FONT,
    fontSize: 14,
    fontWeight: "600",
  },
  loginButton: {
    backgroundColor: "#18AEE6",
    minHeight: 50,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#18AEE6",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.30,
    shadowRadius: 10,
    elevation: 4,
  },
  loginButtonBusy: {
    opacity: 0.78,
  },
  loginText: {
    color: "#FFFFFF",
    fontFamily: AUTH_FONT,
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 14,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(255, 255, 255, 0.20)",
  },
  dividerText: {
    color: "rgba(255, 255, 255, 0.55)",
    fontFamily: AUTH_FONT,
    fontSize: 13,
    fontWeight: "600",
    paddingHorizontal: 12,
    letterSpacing: 0.5,
  },
  googleButton: {
    minHeight: 50,
    borderRadius: 14,
    backgroundColor: "rgba(248, 250, 252, 0.95)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  googleIconContainer: {
    marginRight: 10,
  },
  googleText: {
    color: "#0F172A",
    fontFamily: AUTH_FONT,
    fontSize: 15,
    fontWeight: "600",
  },
  bottomLinkRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 18,
  },
  bottomRegularText: {
    color: "rgba(255, 255, 255, 0.75)",
    fontFamily: AUTH_FONT,
    fontSize: 14,
  },
  signUpLinkText: {
    color: AUTH_ACCENT_ORANGE,
    fontFamily: AUTH_FONT,
    fontSize: 14,
    fontWeight: "700",
  },
  footerTagline: {
    color: "rgba(255, 255, 255, 0.45)",
    fontFamily: AUTH_FONT,
    fontSize: 12,
    textAlign: "center",
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  emailOptionsBox: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "rgba(24, 174, 230, 0.3)",
    borderRadius: 12,
    marginTop: -8,
    marginBottom: 12,
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 4,
  },
  emailOption: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  emailOptionText: {
    marginLeft: 10,
    color: "#0F172A",
    fontFamily: AUTH_FONT,
    fontSize: 14,
  },
});

export default styles;
