//===== (Imports) ======
import { StyleSheet } from "react-native";
import {
  AUTH_ACCENT_ORANGE,
  AUTH_FONT,
} from "@/features/auth/constants/styles";

//===== (LoginScreen Styles) ======
const styles = StyleSheet.create({
  outerContainer: {
    flex: 1,
    backgroundColor: "#000000",
  },
  backgroundImage: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
  backgroundImageStyle: {
    resizeMode: "cover",
    opacity: 0.55,
  },
  fullOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(12, 18, 34, 0.50)",
  },
  safeArea: {
    flex: 1,
  },
  container: {
    flex: 1,
  },
  screen: {
    flex: 1,
    width: "100%",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  headerBlock: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  logoImage: {
    width: 220,
    height: 84,
    marginBottom: 8,
  },
  welcome: {
    color: "#0F172A",
    fontFamily: AUTH_FONT,
    fontSize: 22,
    fontWeight: "700",
    letterSpacing: -0.3,
    textAlign: "center",
  },
  subtitle: {
    color: "#64748B",
    fontFamily: AUTH_FONT,
    fontSize: 13,
    marginTop: 4,
    textAlign: "center",
    paddingHorizontal: 8,
    lineHeight: 18,
  },
  formSection: {
    width: "100%",
    paddingHorizontal: 0,
  },
  formCard: {
    width: "100%",
    maxWidth: 430,
    alignSelf: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    paddingHorizontal: 22,
    paddingTop: 24,
    paddingBottom: 22,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 8,
  },
  label: {
    color: "#1E293B",
    fontFamily: AUTH_FONT,
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 8,
  },
  inputWrapper: {
    minHeight: 50,
    backgroundColor: "#F8FAFC",
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  inputWrapperFocused: {
    borderColor: "#18AEE6",
    backgroundColor: "#FFFFFF",
  },
  inputIcon: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    minHeight: 44,
    color: "#0F172A",
    fontFamily: AUTH_FONT,
    fontSize: 15,
    paddingVertical: 8,
  },
  passwordToggle: {
    padding: 6,
    marginLeft: 4,
  },
  rememberAndForgotRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 2,
    marginBottom: 18,
  },
  rememberPressable: {
    flexDirection: "row",
    alignItems: "center",
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    backgroundColor: "#F8FAFC",
    borderWidth: 1.5,
    borderColor: "#CBD5E1",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
  },
  checkboxActive: {
    backgroundColor: "#18AEE6",
    borderColor: "#18AEE6",
  },
  rememberText: {
    color: "#334155",
    fontFamily: AUTH_FONT,
    fontSize: 14,
    fontWeight: "500",
  },
  forgotPasswordLink: {
    color: "#18AEE6",
    fontFamily: AUTH_FONT,
    fontSize: 14,
    fontWeight: "600",
  },
  loginButton: {
    backgroundColor: "#18AEE6",
    minHeight: 50,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#18AEE6",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.30,
    shadowRadius: 10,
    elevation: 4,
  },
  loginButtonBusy: {
    opacity: 0.78,
  },
  loginText: {
    color: "#FFFFFF",
    fontFamily: AUTH_FONT,
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 14,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#E2E8F0",
  },
  dividerText: {
    color: "#94A3B8",
    fontFamily: AUTH_FONT,
    fontSize: 13,
    fontWeight: "600",
    paddingHorizontal: 12,
    letterSpacing: 0.5,
  },
  googleButton: {
    minHeight: 50,
    borderRadius: 14,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  googleIconContainer: {
    marginRight: 10,
  },
  googleText: {
    color: "#0F172A",
    fontFamily: AUTH_FONT,
    fontSize: 15,
    fontWeight: "600",
  },
  bottomLinkRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 20,
  },
  bottomRegularText: {
    color: "#64748B",
    fontFamily: AUTH_FONT,
    fontSize: 14,
  },
  signUpLinkText: {
    color: "#18AEE6",
    fontFamily: AUTH_FONT,
    fontSize: 14,
    fontWeight: "700",
  },
  footerTagline: {
    color: "rgba(255, 255, 255, 0.70)",
    fontFamily: AUTH_FONT,
    fontSize: 12,
    textAlign: "center",
    paddingVertical: 14,
    paddingHorizontal: 20,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  pressableWrapper: {
    width: "100%",
  },
  emailOptionsBox: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "rgba(24, 174, 230, 0.3)",
    borderRadius: 12,
    marginTop: -8,
    marginBottom: 12,
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 4,
  },
  emailOption: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  emailOptionText: {
    marginLeft: 10,
    color: "#0F172A",
    fontFamily: AUTH_FONT,
    fontSize: 14,
  },
});

export default styles;
