//===== (Imports) ======
import { Platform, StyleSheet } from 'react-native';

//===== (Constants) ======
const appFont = Platform.select({
  android: 'sans-serif',
  ios: 'Helvetica Neue',
  default: 'System',
});

const BATARI_LOGO_SIZE = 100;

//===== (Styles) ======
const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#0C1222",
  },
  container: {
    flex: 1,
    backgroundColor: "#0C1222",
  },
  scroll: {
    flex: 1,
    backgroundColor: "#0C1222",
  },
  scrollContent: {
    flexGrow: 1,
  },
  screen: {
    flex: 1,
    width: "100%",
    backgroundColor: "#0C1222",
  },
  hero: {
    height: 188,
    justifyContent: "center",
    overflow: "hidden",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.05)",
  },
  backgroundPhoto: {
    opacity: 0.24,
  },
  heroOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(12, 18, 34, 0.62)",
  },
  brandBlock: {
    alignItems: "center",
    paddingTop: 14,
  },
  logoFrame: {
    width: BATARI_LOGO_SIZE,
    height: BATARI_LOGO_SIZE,
    borderRadius: BATARI_LOGO_SIZE / 2,
    backgroundColor: "#0C1222",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.18)",
    marginBottom: 8,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.28,
    shadowRadius: 16,
    elevation: 8,
  },
  logo: {
    width: BATARI_LOGO_SIZE,
    height: BATARI_LOGO_SIZE,
    borderRadius: BATARI_LOGO_SIZE / 2,
  },
  tagline: {
    color: "rgba(255, 255, 255, 0.82)",
    fontFamily: appFont,
    fontSize: 13,
    fontWeight: "400",
    letterSpacing: 0,
    textAlign: "center",
    marginTop: 14,
  },
  welcome: {
    color: "#FFFFFF",
    fontFamily: appFont,
    fontSize: 31,
    fontWeight: "600",
    letterSpacing: 0,
    marginTop: 8,
  },
  formSection: {
    flex: 1,
    width: "100%",
    paddingHorizontal: 22,
    paddingTop: 45,
    paddingBottom: 12,
  },
  formSurface: {
    width: "100%",
    maxWidth: 430,
    alignSelf: "center",
  },
  label: {
    fontSize: 18,
    color: "#F8FAFC",
    fontFamily: appFont,
    fontWeight: "500",
    letterSpacing: 0,
    marginBottom: 8,
  },
  inputWrapper: {
    minHeight: 48,
    backgroundColor: "#F8FAFC",
    borderRadius: 8,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 2,
  },
  inputWrapperFocused: {
    borderColor: "#18AEE6",
    shadowColor: "#18AEE6",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.24,
    shadowRadius: 12,
    elevation: 4,
  },
  input: {
    flex: 1,
    fontSize: 17,
    color: "#111827",
    fontFamily: appFont,
    fontWeight: "400",
    letterSpacing: 0,
    paddingVertical: 12,
  },
  rememberRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: -8,
    marginBottom: 22,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 4,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.9)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 5,
    elevation: 2,
  },
  checkboxActive: {
    backgroundColor: "#1DA8DF",
    borderColor: "#1DA8DF",
  },
  rememberText: {
    color: "#F8FAFC",
    fontFamily: appFont,
    fontSize: 18,
    fontWeight: "400",
    letterSpacing: 0,
  },
  loginButton: {
    backgroundColor: "#18AEE6",
    minHeight: 58,
    borderRadius: 29,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 22,
    shadowColor: "#18AEE6",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.32,
    shadowRadius: 16,
    elevation: 6,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.18)",
  },
  loginButtonBusy: {
    opacity: 0.75,
  },
  loginText: {
    color: "#FFFFFF",
    fontFamily: appFont,
    fontSize: 18,
    fontWeight: "400",
    letterSpacing: 0,
  },
  linkRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 12,
  },
  link: {
    color: "#168CC8",
    fontFamily: appFont,
    fontSize: 16,
    fontWeight: "500",
    letterSpacing: 0,
  },
  orText: {
    color: "#168CC8",
    fontFamily: appFont,
    fontSize: 16,
    fontWeight: "500",
    letterSpacing: 0,
    textAlign: "center",
    marginTop: 20,
    marginBottom: 18,
  },
  googleButton: {
    minHeight: 58,
    borderRadius: 29,
    backgroundColor: "#F8FAFC",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 18,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.14,
    shadowRadius: 12,
    elevation: 3,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.18)",
  },
  googleText: {
    color: "#111827",
    fontFamily: appFont,
    fontSize: 18,
    fontWeight: "500",
    letterSpacing: 0,
  },
  facebookButton: {
    minHeight: 58,
    borderRadius: 29,
    backgroundColor: "#3D68D5",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#1D4ED8",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.24,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
  },
  facebookText: {
    color: "#FFFFFF",
    fontFamily: appFont,
    fontSize: 18,
    fontWeight: "500",
    letterSpacing: 0,
  },
  socialIcon: {
    marginRight: 14,
  },
  footerPhotoBlock: {
    height: 52,
    backgroundColor: "#0C1222",
    overflow: "hidden",
  },
  footerPhoto: {
    opacity: 0.18,
  },
  emailOptionsBox: {
    backgroundColor: "#FFFFFF",
    borderTopWidth: 0,
    borderWidth: 1,
    borderColor: "rgba(24, 174, 230, 0.25)",
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    marginTop: -1,
    marginBottom: 16,
    overflow: "hidden",
  },
  emailOption: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(15, 23, 42, 0.08)",
  },
  emailOptionText: {
    marginLeft: 10,
    color: "#111827",
    fontFamily: appFont,
    fontSize: 15,
  },
  emailInputOpen: {
    marginBottom: 0,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
});


export default styles;
