//===== (Imports) ======
import { appColors, appFont } from "@/config/theme";
import { StyleSheet } from "react-native";
import {
  BATTERY_BUBBLE_CONFIG,
  CHART_HEIGHT,
  LANDSCAPE_CHART_LAYOUT,
  MENU_RIGHT_OFFSET,
  MENU_TOP_OFFSET,
  PLANT_HEADER_BOX,
  PLANT_HEADER_BUTTON,
  PLANT_HEADER_TEXT,
  POWER_CHART_LAYOUT,
  POWER_FLOW_OVERLAY_LAYOUT,
  WEATHER_LAYOUT,
} from "../constants/overviewConstants";

//===== (Styles) ======
const styles = StyleSheet.create({
  //===== (Base Layout) ======
  safeArea: {
    flex: 1,
    backgroundColor: appColors.bubble,
  },
  container: {
    flex: 1,
    backgroundColor: appColors.screen,
  },
  //===== (Plant Header) ======
  stickyTopBar: {
    width: "100%",
    maxWidth: 640,
    alignSelf: "center",

    minHeight: PLANT_HEADER_BOX.minHeight,
    marginHorizontal: 0,
    marginTop: 0,
    marginBottom: PLANT_HEADER_BOX.marginBottom,

    paddingVertical: PLANT_HEADER_BOX.paddingVertical,
    borderRadius: 0,

    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",

    backgroundColor: appColors.bubble,

    borderTopWidth: 0,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderBottomColor: "rgba(8,174,234,0.22)",

    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
    zIndex: 10,
  },
  leftHeader: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    marginRight: 14,
  },
  backButton: {
    width: PLANT_HEADER_BUTTON.backButtonSize,
    height: PLANT_HEADER_BUTTON.backButtonSize,
    justifyContent: "center",
    alignItems: "center",
    marginRight: PLANT_HEADER_BUTTON.backMarginRight,
    backgroundColor: "transparent",
    transform: [
      { translateX: PLANT_HEADER_BUTTON.backOffsetX },
      { translateY: PLANT_HEADER_BUTTON.backOffsetY },
    ],
  },
  plantName: {
    fontSize: PLANT_HEADER_TEXT.nameFontSize,
    lineHeight: PLANT_HEADER_TEXT.nameLineHeight,
    fontWeight: "700",
    color: appColors.text,
    fontFamily: appFont,
    letterSpacing: 0,
  },
  plantTitleBlock: {
    flex: 1,
  },
  plantMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: PLANT_HEADER_TEXT.productionMarginTop,
  },
  plantProductionMeta: {
    color: appColors.accent,
    fontFamily: appFont,
    fontSize: PLANT_HEADER_TEXT.productionFontSize,
    lineHeight: PLANT_HEADER_TEXT.productionLineHeight,
    fontWeight: "800",
    letterSpacing: 0,
  },
  menuButton: {
    width: PLANT_HEADER_BUTTON.menuButtonSize,
    height: PLANT_HEADER_BUTTON.menuButtonSize,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  //===== (Menu and Loading State) ======
  menuOverlay: {
    flex: 1,
    backgroundColor: "transparent",
    alignItems: "flex-end",
    paddingTop: MENU_TOP_OFFSET,
    paddingRight: MENU_RIGHT_OFFSET,
  },
  menuPopup: {
    width: 176,
    borderRadius: 18,
    backgroundColor: appColors.bubble,
    borderWidth: 1,
    borderColor: "rgba(8,174,234,0.22)",
    paddingVertical: 8,
    shadowColor: appColors.accent,
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  menuItem: {
    minHeight: 48,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  menuItemText: {
    color: appColors.text,
    fontFamily: appFont,
    fontSize: 15,
    fontWeight: "600",
  },
  refreshLoadingOverlay: {
    flex: 1,
    backgroundColor: "rgba(2,7,19,0.72)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 28,
  },
  refreshLoadingCard: {
    width: "100%",
    maxWidth: 280,
    borderRadius: 22,
    backgroundColor: appColors.bubble,
    borderWidth: 1,
    borderColor: "rgba(8,174,234,0.2)",
    paddingVertical: 28,
    paddingHorizontal: 22,
    alignItems: "center",
    shadowColor: appColors.accent,
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  refreshLoadingTitle: {
    marginTop: 16,
    color: appColors.text,
    fontFamily: appFont,
    fontSize: 20,
    fontWeight: "700",
    letterSpacing: 0,
  },
  content: {
    width: "100%",
    maxWidth: 640,
    alignSelf: "center",
    marginTop: 4,
    paddingHorizontal: 16,
    paddingBottom: 90,
  },
  //===== (Chart Controls) ======
  segmentCard: {
    marginTop: 16,
    backgroundColor: appColors.bubble,
    borderRadius: WEATHER_LAYOUT.cardRadius,
    paddingTop: 16,
    paddingBottom: 28,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "rgba(8,174,234,0.22)",
    shadowColor: appColors.accent,
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 7,
    overflow: "hidden",
  },
  segmentRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: appColors.input,
    borderRadius: 14,
    padding: 4,
    marginBottom: 16,
  },
  segmentButton: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 10,
    borderRadius: 10,
  },
  segmentButtonActive: {
    backgroundColor: appColors.accent,
  },
  segmentText: {
    color: appColors.textMuted,
    fontFamily: appFont,
    fontSize: 14,
  },
  segmentTextActive: {
    color: appColors.text,
    fontSize: 14,
    fontWeight: "700",
  },
  dateText: {
    fontSize: 16,
    fontWeight: "600",
    color: appColors.textSoft,
    fontFamily: appFont,
  },
  //===== (Chart Presentation) ======
  chartSection: {
    marginTop: 14,
    paddingTop: 2,
  },
  chartLandscapeSection: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 0,
    paddingTop: 0,
  },
  chartCanvasWrap: {
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  chartMarkerTouchArea: {
    position: "absolute",
    left: 0,
    top: 0,
    zIndex: 2,
  },
  chartMarkerTriangle: {
    position: "absolute",
    width: 0,
    height: 0,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    backgroundColor: "transparent",
    shadowColor: "#FFFFFF",
    shadowOpacity: 0.32,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  chartLoadingWrap: {
    minHeight: CHART_HEIGHT,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 14,
    paddingVertical: 26,
  },
  chartLoadingText: {
    marginTop: 12,
    color: appColors.textSoft,
    fontFamily: appFont,
    fontSize: 13,
    fontWeight: "600",
    textAlign: "center",
  },
  chartSwitchRow: {
    marginTop: POWER_CHART_LAYOUT.switchMarginTop,
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    flexWrap: "nowrap",
    width: "100%",
    paddingHorizontal: 2,
  },
  chartSwitchItem: {
    flex: 1,
    minWidth: 0,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  chartSwitchButton: {
    width: POWER_CHART_LAYOUT.switchWidth,
    height: POWER_CHART_LAYOUT.switchHeight,
    borderRadius: POWER_CHART_LAYOUT.switchHeight / 2,
    padding: POWER_CHART_LAYOUT.switchPadding,
    justifyContent: "center",
  },
  chartSwitchKnob: {
    width:
      POWER_CHART_LAYOUT.switchHeight - POWER_CHART_LAYOUT.switchPadding * 2,
    height:
      POWER_CHART_LAYOUT.switchHeight - POWER_CHART_LAYOUT.switchPadding * 2,
    borderRadius: POWER_CHART_LAYOUT.switchHeight / 2,
  },
  chartSwitchLabel: {
    marginTop: 5,
    width: "100%",
    fontFamily: appFont,
    fontSize: 9,
    lineHeight: 12,
    fontWeight: "700",
    letterSpacing: 0,
    textAlign: "center",
  },
  chartSelectedInfo: {
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: "rgba(2,7,19,0.38)",
    borderWidth: 1,
    borderColor: "rgba(248,250,252,0.1)",
  },
  chartSelectedInfoHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 9,
  },
  chartSelectedInfoTitle: {
    color: appColors.text,
    fontFamily: appFont,
    fontSize: 13,
    fontWeight: "800",
  },
  chartSelectedInfoMeta: {
    flexShrink: 1,
    color: appColors.textSoft,
    fontFamily: appFont,
    fontSize: 12,
    fontWeight: "700",
    textAlign: "right",
  },
  chartSelectedInfoGrid: {
    gap: 7,
  },
  chartSelectedInfoItem: {
    minHeight: 22,
    flexDirection: "row",
    alignItems: "center",
  },
  chartSelectedInfoDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    marginRight: 7,
  },
  chartSelectedInfoLabel: {
    flex: 1,
    minWidth: 0,
    color: appColors.textMuted,
    fontFamily: appFont,
    fontSize: 11,
    fontWeight: "700",
  },
  chartSelectedInfoValue: {
    flexShrink: 0,
    color: appColors.text,
    fontFamily: appFont,
    fontSize: 11,
    fontWeight: "800",
    textAlign: "right",
  },
  chartSavePdfButton: {
    minHeight: 38,
    marginTop: 12,
    borderRadius: 11,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: appColors.accent,
  },
  chartSavePdfButtonDisabled: {
    opacity: 0.68,
  },
  chartSavePdfText: {
    color: appColors.text,
    fontFamily: appFont,
    fontSize: 13,
    fontWeight: "800",
  },
  //===== (Landscape Chart) ======
  chartLandscapeSafeArea: {
    flex: 1,
    backgroundColor: appColors.screen,
  },
  chartLandscapeHeader: {
    minHeight: LANDSCAPE_CHART_LAYOUT.headerHeight,
    paddingHorizontal: 4,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: appColors.screen,
  },
  chartLandscapeBackButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  chartLandscapeBody: {
    flex: 1,
    paddingHorizontal: LANDSCAPE_CHART_LAYOUT.horizontalPadding,
    paddingBottom: LANDSCAPE_CHART_LAYOUT.bottomPadding,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: appColors.screen,
  },
  chartLandscapeFrame: {
    width: "100%",
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  //===== (Date Picker) ======
  dayPickerWrap: {
    marginBottom: 8,
  },
  dayPickerContent: {
    paddingRight: 12,
    paddingBottom: 8,
  },
  dayChip: {
    minWidth: 42,
    height: 36,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
    backgroundColor: "transparent",
  },
  dayChipActive: {
    backgroundColor: appColors.accent,
    borderColor: appColors.accent,
  },
  dayChipText: {
    fontSize: 14,
    fontWeight: "600",
    color: "rgba(255,255,255,0.65)",
  },
  dayChipTextActive: {
    color: appColors.text,
  },
  monthChip: {
    minWidth: 96,
    height: 36,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
    paddingHorizontal: 14,
    backgroundColor: "transparent",
  },
  monthChipActive: {
    backgroundColor: appColors.accent,
    borderColor: appColors.accent,
  },
  monthChipText: {
    fontSize: 14,
    fontWeight: "600",
    color: "rgba(255,255,255,0.65)",
  },
  monthChipTextActive: {
    color: appColors.text,
  },
  yearChip: {
    minWidth: 74,
    height: 36,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
    paddingHorizontal: 14,
    backgroundColor: "transparent",
  },
  yearChipActive: {
    backgroundColor: appColors.accent,
    borderColor: appColors.accent,
  },
  yearChipText: {
    fontSize: 14,
    fontWeight: "600",
    color: "rgba(255,255,255,0.65)",
  },
  yearChipTextActive: {
    color: appColors.text,
  },
  //===== (Power Flow) ======
  powerFlowSection: {
    marginTop: 8,
    marginBottom: 16,
    backgroundColor: "transparent",
  },
  houseImageOnly: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  houseImage: {
    width: "100%",
  },
  powerFlowWrapper: {
    backgroundColor: appColors.bubble,
    borderRadius: WEATHER_LAYOUT.cardRadius,
    paddingTop: 20,
    paddingBottom: 28,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "rgba(8,174,234,0.22)",
    shadowColor: appColors.accent,
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 7,
    overflow: "visible",
    alignItems: "center",
  },
  powerFlowTitle: {
    alignSelf: "flex-start",
    color: appColors.text,
    fontFamily: appFont,
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "350",
    letterSpacing: 0,
    textAlign: "left",
    marginLeft: 4,
    marginBottom: 8,
  },
  houseImageOnly: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 50,
  },
  houseOverlayWrap: {
    position: "relative",
    width: "100%",
    maxWidth: 420,
    alignSelf: "center",
    height: 360,
    alignItems: "center",
    justifyContent: "center",
  },
  dataSourceDropdownRow: {
    alignSelf: "center",
    width: "100%",
    maxWidth: 420,
    flexDirection: "row",
    justifyContent: "flex-end",
    paddingHorizontal: 8,
    marginTop: -8,
    marginBottom: 12,
    zIndex: 999,
  },
  dataSourceDropdownWrap: {
    width: 144,
    zIndex: 999,
  },
  dataSourceDropdownButton: {
    minHeight: 32,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 5,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
    backgroundColor: "rgba(2,7,19,0.85)",
    borderWidth: 1,
    borderColor: "rgba(8,174,234,0.38)",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
  },
  dataSourceDropdownButtonOpen: {
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  dataSourceDropdownText: {
    flex: 1,
    minWidth: 0,
    fontFamily: appFont,
    fontSize: 12,
    fontWeight: "700",
  },
  dataSourceDropdownMenu: {
    position: "absolute",
    top: 34,
    left: 0,
    right: 0,
    zIndex: 999,
    backgroundColor: "rgba(10,18,34,0.98)",
    borderWidth: 1,
    borderColor: "rgba(8,174,234,0.45)",
    borderRadius: 14,
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 30,
    overflow: "hidden",
  },
  dataSourceDropdownItem: {
    minHeight: 36,
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  dataSourceDropdownItemText: {
    fontFamily: appFont,
    fontSize: 12,
    fontWeight: "700",
  },
  gridPointerOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  gridPointerDotGlow: {
    position: "absolute",
    top: 0,
    left: 0,
  },
  gridPointerDot: {
    position: "absolute",
    top: 0,
    left: 0,
  },
  infoBubble: {
    position: "absolute",
    width: POWER_FLOW_OVERLAY_LAYOUT.bubbleWidth,
    height: POWER_FLOW_OVERLAY_LAYOUT.bubbleHeight,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.7)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  infoBubbleLight: {
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(8,174,234,0.34)",
    shadowColor: "#08AEEA",
    shadowOpacity: 0.1,
    elevation: 3,
  },
  infoBubbleLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1F2937",
    maxWidth: "100%",
    textAlign: "center",
  },
  infoBubbleValue: {
    fontSize: 16,
    fontWeight: "800",
    color: "#111827",
    marginTop: 2,
    maxWidth: "100%",
    textAlign: "center",
  },
  pvBubble: {
    overflow: "hidden",
  },
  gridBubble: {
    overflow: "hidden",
  },
  batteryBubble: {
    overflow: "hidden",
  },
  loadBubble: {
    overflow: "hidden",
  },
  batteryLabel: {
    fontSize: BATTERY_BUBBLE_CONFIG.titleFontSize,
    fontWeight: BATTERY_BUBBLE_CONFIG.titleFontWeight,
    color: "#1F2937",
    maxWidth: "100%",
    textAlign: "center",
  },
  batteryValue: {
    fontSize: BATTERY_BUBBLE_CONFIG.valueFontSize,
    fontWeight: BATTERY_BUBBLE_CONFIG.valueFontWeight,
    color: "#111827",
    marginTop: 2,
    maxWidth: "100%",
    textAlign: "center",
  },
  //===== (Month Navigation) ======
  monthNavigation: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
    paddingHorizontal: 8,
  },
  monthNavigationText: {
    fontSize: 16,
    fontWeight: "600",
  },
});

export default styles;
