//===== (Imports) ======
import { appColors, appFont } from "@/config/theme";
import { StyleSheet } from "react-native";

//===== (Plant Styles) ======
export const plantStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: appColors.screen,
  },
  contentWrapper: {
    flex: 1,
    width: "100%",
    maxWidth: 640,
    alignSelf: "center",
    paddingHorizontal: 16,
    paddingTop: 4,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  title: {
    fontSize: 22,
    fontWeight: "700",
    color: appColors.text,
    fontFamily: appFont,
  },
  addButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
    backgroundColor: appColors.bubble,
    borderWidth: 1,
    borderColor: appColors.bubbleBorder,
  },
  searchBox: {
    marginTop: 6,
    marginBottom: 8,
    backgroundColor: appColors.bubble,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: appColors.bubbleBorder,
    paddingHorizontal: 12,
  },
  searchInput: {
    height: 38,
    fontSize: 13.5,
    color: appColors.text,
    fontFamily: appFont,
  },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    marginTop: 10,
    color: appColors.textMuted,
    fontFamily: appFont,
    fontSize: 15,
  },
  emptyText: {
    textAlign: "center",
    color: appColors.textMuted,
    fontFamily: appFont,
    marginTop: 24,
    fontSize: 15,
  },
  headerTextGroup: {
    flex: 1,
  },
  headerSubtitle: {
    fontSize: 12,
    fontFamily: appFont,
    color: appColors.textMuted,
    marginTop: 1,
  },
  fleetCard: {
    marginTop: 4,
    marginBottom: 4,
    borderRadius: 14,
    borderWidth: 1,
    paddingVertical: 7,
    paddingHorizontal: 10,
    backgroundColor: appColors.bubble,
    borderColor: appColors.bubbleBorder,
  },
  fleetHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 5,
  },
  fleetTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  fleetTitleText: {
    fontSize: 11,
    fontWeight: "700",
    fontFamily: appFont,
    color: appColors.text,
    letterSpacing: 0.2,
  },
  fleetPill: {
    paddingHorizontal: 6,
    paddingVertical: 1.5,
    borderRadius: 6,
    backgroundColor: "rgba(24, 174, 230, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(24, 174, 230, 0.25)",
  },
  fleetPillText: {
    fontSize: 9.5,
    fontWeight: "700",
    color: "#18AEE6",
    fontFamily: appFont,
  },
  fleetStatsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  fleetStatItem: {
    flex: 1,
    paddingVertical: 3,
    paddingHorizontal: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "transparent",
  },
  fleetStatValue: {
    fontSize: 14.5,
    fontWeight: "800",
    fontFamily: appFont,
    color: appColors.text,
  },
  fleetStatLabel: {
    fontSize: 10,
    fontWeight: "500",
    color: appColors.textMuted,
    fontFamily: appFont,
    marginTop: 1,
  },
  fleetDivider: {
    width: 1,
    height: 18,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    marginHorizontal: 4,
  },
  searchCountText: {
    fontSize: 11,
    fontFamily: appFont,
    color: appColors.textMuted,
    marginTop: -4,
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  navigationOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: appColors.screen,
  },
  navigationLoadingText: {
    marginTop: 12,
    color: appColors.textSoft,
    fontFamily: appFont,
    fontSize: 15,
    fontWeight: "600",
  },
});
